<h1><strong>Bag of Words(BoW)</strong></h1>

The name "bag of words" comes from the fact that model ignores the grammer, word order, and context of the text.

It simply looks at whether a word occurs in the document and how many time it appears.

Imagine putting all the words from a sentence into a physical bag; you lose the order of the words, but you can still count how many times "apple" or "orange" was thrown in.

<h3><strong>How it works</strong></h3>

- Step01: Tokenization
- Step02: Vocabulary building
- Step03: Vectorization(encoding)

<h3><strong>Pros & Cons</strong></h3>

- Pros: Extremely simple ot understand and implement. Great for basic document Classification.

- cons: Loss of semantic meaning

- cons: High Dimensionality

In [5]:
import pandas as pd
from sklearn.feature_extraction.text import  CountVectorizer

data = {
    'Review':[
    "The movie was great great and amazing",
    "The movie was bad and boring",
    "Great movie, I loved the acting",
    "It was a boring movie"]
}

df = pd.DataFrame(data)

In [6]:
df

                                  Review
0  The movie was great great and amazing
1           The movie was bad and boring
2        Great movie, I loved the acting
3                  It was a boring movie

In [7]:
vectorizer = CountVectorizer(stop_words="english")

bow_matrix = vectorizer.fit_transform(df['Review'])

bow_df = pd.DataFrame(
    bow_matrix.toarray(),columns=vectorizer.get_feature_names_out()
)

In [8]:
bow_df

   acting  amazing  bad  boring  great  loved  movie
0       0        1    0       0      2      0      1
1       0        0    1       1      0      0      1
2       1        0    0       0      1      1      1
3       0        0    0       1      0      0      1

<h1><strong>N-grams</strong></h1>

An N-gram is a contiguous sequence of n items from a given sample to text.In NLP, "items" usually refers to words.

- Unigram(n=1): Single words (This is exactly what the standard Bag of words uses.)
- Bigram(n=2): Pairs of consecutive words.
- Trigram(n=3): Group of three consecutive words.

In [9]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer


data = {
    'Review':[
    "The movie was great great and amazing",
    "The movie was bad and boring",
    "Great movie, I loved the acting",
    "It was a boring movie"]
}

df = pd.DataFrame(data)

In [26]:
df

                                  Review
0  The movie was great great and amazing
1           The movie was bad and boring
2        Great movie, I loved the acting
3                  It was a boring movie

In [38]:
vectorizer = CountVectorizer(ngram_range=(1,3),stop_words="english")

ngrams_matrix = vectorizer.fit_transform(df['Review'])

ngram_df = pd.DataFrame(ngrams_matrix.toarray(),columns=vectorizer.get_feature_names_out())

ngram_df

   acting  amazing  bad  ...  movie great great  movie loved  movie loved acting
0       0        1    0  ...                  1            0                   0
1       0        0    1  ...                  0            0                   0
2       1        0    0  ...                  0            1                   1
3       0        0    0  ...                  0            0                   0

[4 rows x 21 columns]